[build]
builder = "nixpacks"

[deploy]
startCommand = "python src/ui/status_server.py --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/status"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[variables]
FLASK_ENV = "production"
PYTHONPATH = "/app"